"use client";

import { useEffect, useMemo, useState } from "react";
import { Boxes, Download, Mail, Megaphone, Pencil, Plus, RefreshCw, RotateCcw, Save, Search, Trash2, Users } from "lucide-react";
import { toast } from "sonner";

type Product = { id:number; sku:string; name:string; category:string; description:string; price:number; stock:number; accent:string; imageUrl?:string|null; active?:boolean };
type Item = { id:number; productName:string; quantity:number; unitPrice:number };
type Notice = { id:number; template:string; deliveryStatus:string; createdAt:string };
type Order = { id:number; orderNumber:string; customerAlias:string; customerEmail?:string|null; subtotal:number; tax:number; shipping:number; discount:number; total:number; status:string; createdAt:string; items:Item[]; notifications?:Notice[] };
type EventRow = { id:number; eventType:string; sessionId:string; payload:string; createdAt:string };
type Customer = { email:string; name:string; orders:number; spend:number; lastOrder:string; favoriteProduct:string; segment:string };
type Coupon = { id:number; code:string; discountPercent:number; minimumAmount:number; maxUses:number; usedCount:number; startsAt:string; endsAt:string; active:boolean };
type ReturnRow = { id:number; orderId:number; reason:string; details:string; status:string; refundAmount:number; createdAt:string; order?:Order|null };
type Tab = "catalog"|"crm"|"communications"|"reports"|"returns"|"promotions";
const euro = new Intl.NumberFormat("es-ES", { style:"currency", currency:"EUR" });
const today = () => new Date().toISOString().slice(0,10);
const nextMonth = () => { const d = new Date(); d.setMonth(d.getMonth()+1); return d.toISOString().slice(0,10); };
const emptyProduct = { sku:"", name:"", category:"Visual", description:"", price:0, stock:10, imageUrl:"" };

export default function AdminHub({ orders, events, onProductsChanged }:{ orders:Order[]; events:EventRow[]; onProductsChanged:(p:Product[])=>void }) {
  const [tab,setTab]=useState<Tab>("catalog"), [products,setProducts]=useState<Product[]>([]), [customers,setCustomers]=useState<Customer[]>([]), [coupons,setCoupons]=useState<Coupon[]>([]), [returns,setReturns]=useState<ReturnRow[]>([]), [busy,setBusy]=useState(false);
  const [productForm,setProductForm]=useState(emptyProduct), [editing,setEditing]=useState<Product|null>(null), [query,setQuery]=useState("");
  const [couponForm,setCouponForm]=useState({code:"",discountPercent:10,minimumAmount:40,maxUses:100,startsAt:today(),endsAt:nextMonth()});
  const [selectedOrder,setSelectedOrder]=useState<number>(orders[0]?.id ?? 0), [template,setTemplate]=useState("PAGO_SIMULADO");
  const load = async () => {
    setBusy(true);
    try { const [p,c,r,crm]=await Promise.all([fetch("/api/products?all=1"),fetch("/api/coupons"),fetch("/api/returns"),fetch("/api/crm")]); const [pd,cd,rd,md]=await Promise.all([p.json(),c.json(),r.json(),crm.json()]); setProducts(pd.products||[]); setCoupons(cd.coupons||[]); setReturns(rd.returns||[]); setCustomers(md.customers||[]); }
    catch { toast.error("No se pudieron cargar los datos de gestión"); } finally { setBusy(false); }
  };
  useEffect(()=>{ const timer=window.setTimeout(()=>void load(),0); return()=>window.clearTimeout(timer); },[]);
  const saveProduct=async(e:React.FormEvent)=>{e.preventDefault(); const body=editing?{...editing}:{...productForm}; const r=await fetch("/api/products",{method:editing?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}); const d=await r.json(); if(!r.ok){toast.error(d.error||"No se pudo guardar");return;} toast.success(editing?"Producto actualizado":"Producto creado"); setEditing(null);setProductForm(emptyProduct);await load();onProductsChanged((await (await fetch("/api/products")).json()).products||[]);};
  const toggleProduct=async(p:Product)=>{const r=await fetch("/api/products",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:p.id,active:!p.active})});if(r.ok){toast.success(p.active?"Producto ocultado":"Producto publicado");await load();onProductsChanged((await (await fetch("/api/products")).json()).products||[]);}};
  const createCoupon=async(e:React.FormEvent)=>{e.preventDefault();const r=await fetch("/api/coupons",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(couponForm)});const d=await r.json();if(!r.ok){toast.error(d.error||"No se pudo crear");return;}toast.success("Promoción creada");setCouponForm({...couponForm,code:""});await load();};
  const toggleCoupon=async(c:Coupon)=>{await fetch("/api/coupons",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:c.id,active:!c.active})});await load();};
  const updateReturn=async(id:number,status:string)=>{const r=await fetch("/api/returns",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,status})});if(r.ok){toast.success(status==="REEMBOLSO_SIMULADO"?"Reembolso simulado registrado":"Devolución actualizada");await load();}};
  const selected=orders.find(o=>o.id===selectedOrder)||orders[0];
  const exportCsv=(kind:"orders"|"products"|"events"|"customers")=>{let rows:(string|number)[][]=[];if(kind==="orders")rows=[["Pedido","Cliente","Email","Estado","Total","Fecha"],...orders.map(o=>[o.orderNumber,o.customerAlias,o.customerEmail||"",o.status,o.total,o.createdAt])];if(kind==="products")rows=[["SKU","Producto","Categoría","Precio","Stock","Visible"],...products.map(p=>[p.sku,p.name,p.category,p.price,p.stock,p.active!==false?"Sí":"No"])];if(kind==="events")rows=[["Evento","Sesión","Datos","Fecha"],...events.map(e=>[e.eventType,e.sessionId,e.payload,e.createdAt])];if(kind==="customers")rows=[["Cliente","Email","Segmento","Pedidos","Gasto","Favorito"],...customers.map(c=>[c.name,c.email,c.segment,c.orders,c.spend,c.favoriteProduct])];const csv=rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(";")).join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob(["\ufeff"+csv],{type:"text/csv;charset=utf-8"}));a.download=`sensoria-${kind}-${today()}.csv`;a.click();URL.revokeObjectURL(a.href);toast.success("Informe CSV descargado");};
  const exportPdf=async()=>{const {jsPDF}=await import("jspdf");const d=new jsPDF();d.setFillColor(16,42,60);d.rect(0,0,210,42,"F");d.setTextColor(255,255,255);d.setFontSize(23);d.text("SENSORIA",16,20);d.setFontSize(10);d.text("INFORME EJECUTIVO ACADEMICO",16,29);d.setTextColor(16,42,60);d.setFontSize(17);d.text("Resumen comercial",16,58);const revenue=orders.reduce((s,o)=>s+o.total,0);[["Ventas registradas",euro.format(revenue)],["Pedidos",String(orders.length)],["Clientes",String(customers.length)],["Productos activos",String(products.filter(p=>p.active!==false).length)],["Devoluciones",String(returns.length)]].forEach((r,i)=>{d.setFillColor(i%2?245:235,241,243);d.rect(16,70+i*17,178,13,"F");d.setFontSize(10);d.text(r[0],21,78+i*17);d.setFont("helvetica","bold");d.text(r[1],188,78+i*17,{align:"right"});d.setFont("helvetica","normal");});d.setFontSize(8);d.setTextColor(100,110,120);d.text("Documento académico. Datos del prototipo Sensoria.",16,275);d.save(`Informe-Sensoria-${today()}.pdf`);toast.success("Informe PDF descargado");};
  const filtered=useMemo(()=>products.filter(p=>`${p.sku} ${p.name} ${p.category}`.toLowerCase().includes(query.toLowerCase())),[products,query]);
  return <main className="backoffice admin-hub">
    <div className="backoffice-head"><div><p className="eyebrow">CENTRO DE OPERACIONES</p><h1>Gestión integral</h1><p>Catálogo, clientes, comunicaciones, informes, devoluciones y promociones.</p></div><button className="admin-refresh" onClick={load} disabled={busy}><RefreshCw/> {busy?"Actualizando…":"Actualizar datos"}</button></div>
    <nav className="admin-tabs" aria-label="Secciones de gestión">
      {([['catalog',Boxes,'Catálogo'],['crm',Users,'CRM'],['communications',Mail,'Comunicaciones'],['reports',Download,'Informes'],['returns',RotateCcw,'Devoluciones'],['promotions',Megaphone,'Promociones']] as const).map(([id,Icon,label])=><button key={id} className={tab===id?"active":""} onClick={()=>setTab(id)}><Icon/>{label}</button>)}
    </nav>
    {tab==="catalog"&&<section className="admin-split"><article className="admin-card"><div className="admin-title"><div><h2>{editing?"Editar producto":"Nuevo producto"}</h2><p>Publica y controla el catálogo permanente.</p></div>{editing&&<button onClick={()=>setEditing(null)}>Cancelar</button>}</div><form className="admin-form" onSubmit={saveProduct}>{([['sku','SKU'],['name','Nombre'],['description','Descripción'],['imageUrl','URL de imagen']] as const).map(([key,label])=><label key={key} className={key==='description'||key==='imageUrl'?"wide":""}>{label}<input required={key!=="imageUrl"} disabled={editing&&key==='sku'} value={String((editing||productForm)[key]??"")} onChange={e=>editing?setEditing({...editing,[key]:e.target.value}):setProductForm({...productForm,[key]:e.target.value})}/></label>)}<label>Categoría<select value={(editing||productForm).category} onChange={e=>editing?setEditing({...editing,category:e.target.value}):setProductForm({...productForm,category:e.target.value})}><option>Visual</option><option>Táctil</option><option>Sonoro</option></select></label><label>Precio<input type="number" min="0.01" step="0.01" value={(editing||productForm).price} onChange={e=>editing?setEditing({...editing,price:+e.target.value}):setProductForm({...productForm,price:+e.target.value})}/></label><label>Stock<input type="number" min="0" value={(editing||productForm).stock} onChange={e=>editing?setEditing({...editing,stock:+e.target.value}):setProductForm({...productForm,stock:+e.target.value})}/></label><button className="admin-primary wide"><Save/>{editing?"Guardar cambios":"Crear producto"}</button></form></article><article className="admin-card"><div className="admin-title"><div><h2>Inventario</h2><p>{products.filter(p=>p.active!==false).length} visibles · {products.filter(p=>p.active===false).length} ocultos</p></div><label className="admin-search"><Search/><input placeholder="Buscar" value={query} onChange={e=>setQuery(e.target.value)}/></label></div><div className="admin-list">{filtered.map(p=><div className={!p.active?"muted-row":""} key={p.id}><span className="product-avatar">{p.imageUrl?<img src={p.imageUrl} alt=""/>:p.name.slice(0,2).toUpperCase()}</span><span><b>{p.name}</b><small>{p.sku} · {p.category} · {euro.format(p.price)}</small></span><strong className={p.stock<8?"danger":""}>{p.stock} uds.</strong><button title="Editar" onClick={()=>setEditing(p)}><Pencil/></button><button title={p.active?"Ocultar":"Publicar"} onClick={()=>toggleProduct(p)}>{p.active?<Trash2/>:<Plus/>}</button></div>)}</div></article></section>}
    {tab==="crm"&&<section className="admin-card"><div className="admin-title"><div><h2>CRM de clientes</h2><p>Segmentación automática basada en pedidos y gasto acumulado.</p></div><span className="admin-badge">{customers.length} perfiles</span></div><div className="crm-kpis"><div><b>{customers.filter(c=>c.segment==='VIP').length}</b><span>VIP</span></div><div><b>{customers.filter(c=>c.segment==='Recurrente').length}</b><span>Recurrentes</span></div><div><b>{euro.format(customers.reduce((s,c)=>s+c.spend,0))}</b><span>Valor total</span></div></div><div className="admin-table"><div className="admin-table-row head"><span>Cliente</span><span>Segmento</span><span>Pedidos</span><span>Gasto</span><span>Producto favorito</span></div>{customers.map(c=><div className="admin-table-row" key={c.email}><span><b>{c.name}</b><small>{c.email}</small></span><span><em className={`segment segment-${c.segment.toLowerCase()}`}>{c.segment}</em></span><span>{c.orders}</span><span>{euro.format(c.spend)}</span><span>{c.favoriteProduct}</span></div>)}</div>{!customers.length&&<div className="admin-empty"><Users/><h3>Aún no hay clientes</h3><p>Se crearán automáticamente cuando se registren compras.</p></div>}</section>}
    {tab==="communications"&&<section className="admin-split"><article className="admin-card"><div className="admin-title"><div><h2>Centro de comunicaciones</h2><p>Previsualiza cada aviso del ciclo de compra.</p></div><span className="admin-badge">Modo académico</span></div><div className="admin-form"><label className="wide">Pedido<select value={selected?.id||0} onChange={e=>setSelectedOrder(+e.target.value)}>{orders.map(o=><option key={o.id} value={o.id}>{o.orderNumber} · {o.customerAlias}</option>)}</select></label><label className="wide">Plantilla<select value={template} onChange={e=>setTemplate(e.target.value)}><option value="PAGO_SIMULADO">Confirmación de compra</option><option value="PREPARACIÓN">Pedido en preparación</option><option value="ENVIADO">Pedido enviado</option><option value="ENTREGADO">Pedido entregado</option></select></label></div>{selected?<div className="email-preview"><div><b>SENSORIA</b><span>Tu pausa empieza aquí</span></div><small>Para: {selected.customerEmail||"correo del cliente"}</small><h3>{template==="PAGO_SIMULADO"?"Hemos recibido tu pedido":template==="PREPARACIÓN"?"Estamos preparando tu ritual":template==="ENVIADO"?"Tu pedido está en camino":"Tu pedido ya ha llegado"}</h3><p>Hola {selected.customerAlias},</p><p>El pedido <b>{selected.orderNumber}</b> ha cambiado al estado <strong>{template.replaceAll('_',' ')}</strong>.</p><div><span>Total</span><b>{euro.format(selected.total)}</b></div><button onClick={()=>toast.success("Previsualización registrada; no se ha enviado un correo real")}>Simular envío</button><small>Prototipo académico: esta acción no envía mensajes externos.</small></div>:<div className="admin-empty"><Mail/><h3>Sin pedidos</h3><p>Completa una compra para previsualizar sus comunicaciones.</p></div>}</article><article className="admin-card"><div className="admin-title"><div><h2>Historial de avisos</h2><p>Trazabilidad por pedido y plantilla.</p></div></div><div className="notice-feed">{orders.flatMap(o=>(o.notifications||[]).map(n=>({...n,order:o.orderNumber,email:o.customerEmail}))).slice(0,16).map(n=><div key={`${n.order}-${n.id}`}><Mail/><span><b>{n.template.replaceAll('_',' ')}</b><small>{n.order} · {n.email}</small></span><em>{n.deliveryStatus==='SENT'?'Enviado':'Simulado'}</em></div>)}</div></article></section>}
    {tab==="reports"&&<section className="admin-card"><div className="admin-title"><div><h2>Informes y exportaciones</h2><p>Descarga datos compatibles con Excel y un resumen ejecutivo en PDF.</p></div></div><div className="report-grid">{([['orders','Pedidos','Importes, estado y cliente'],['products','Productos','Precios, stock y visibilidad'],['events','Eventos','Trazabilidad del canal'],['customers','Clientes CRM','Segmentos y valor acumulado']] as const).map(([id,title,text])=><button key={id} onClick={()=>exportCsv(id)}><Download/><span><b>{title}</b><small>{text}</small></span><em>CSV</em></button>)}<button className="pdf-report" onClick={exportPdf}><Download/><span><b>Informe ejecutivo</b><small>Resumen visual de indicadores</small></span><em>PDF</em></button></div></section>}
    {tab==="returns"&&<section className="admin-card"><div className="admin-title"><div><h2>Gestión de devoluciones</h2><p>Aprueba, rechaza y registra reembolsos simulados.</p></div><span className="admin-badge">{returns.length} solicitudes</span></div><div className="return-list">{returns.map(r=><article key={r.id}><div><span className={`return-status status-${r.status.toLowerCase()}`}>{r.status.replaceAll('_',' ')}</span><h3>{r.order?.orderNumber||`Pedido #${r.orderId}`}</h3><p>{r.reason} · {r.details||"Sin detalles adicionales"}</p><small>{new Date(r.createdAt).toLocaleString("es-ES")} · {euro.format(r.refundAmount)}</small></div><div>{r.status==='SOLICITADA'&&<><button onClick={()=>updateReturn(r.id,'APROBADA')}>Aprobar</button><button className="danger-button" onClick={()=>updateReturn(r.id,'RECHAZADA')}>Rechazar</button></>}{r.status==='APROBADA'&&<button onClick={()=>updateReturn(r.id,'REEMBOLSO_SIMULADO')}>Simular reembolso</button>}</div></article>)}</div>{!returns.length&&<div className="admin-empty"><RotateCcw/><h3>Sin devoluciones pendientes</h3><p>Las solicitudes de clientes aparecerán aquí.</p></div>}</section>}
    {tab==="promotions"&&<section className="admin-split"><article className="admin-card"><div className="admin-title"><div><h2>Nueva promoción</h2><p>Crea cupones con límites y vigencia.</p></div></div><form className="admin-form" onSubmit={createCoupon}><label className="wide">Código<input required value={couponForm.code} onChange={e=>setCouponForm({...couponForm,code:e.target.value.toUpperCase()})} placeholder="CALMA15"/></label><label>Descuento %<input type="number" min="1" max="80" value={couponForm.discountPercent} onChange={e=>setCouponForm({...couponForm,discountPercent:+e.target.value})}/></label><label>Compra mínima<input type="number" min="0" value={couponForm.minimumAmount} onChange={e=>setCouponForm({...couponForm,minimumAmount:+e.target.value})}/></label><label>Usos máximos<input type="number" min="1" value={couponForm.maxUses} onChange={e=>setCouponForm({...couponForm,maxUses:+e.target.value})}/></label><label>Desde<input type="date" value={couponForm.startsAt} onChange={e=>setCouponForm({...couponForm,startsAt:e.target.value})}/></label><label>Hasta<input type="date" value={couponForm.endsAt} onChange={e=>setCouponForm({...couponForm,endsAt:e.target.value})}/></label><button className="admin-primary wide"><Plus/>Crear cupón</button></form></article><article className="admin-card"><div className="admin-title"><div><h2>Cupones activos</h2><p>CALMA10 sigue disponible como cupón académico base.</p></div></div><div className="coupon-list"><article><span><b>CALMA10</b><small>10 % · Cupón base</small></span><em>Siempre activo</em></article>{coupons.map(c=><article className={!c.active?"muted-row":""} key={c.id}><span><b>{c.code}</b><small>{c.discountPercent}% · mín. {euro.format(c.minimumAmount)} · {c.usedCount}/{c.maxUses} usos</small></span><button onClick={()=>toggleCoupon(c)}>{c.active?'Desactivar':'Activar'}</button></article>)}</div></article></section>}
  </main>;
}
