"use client";
import { useEffect, useState } from "react";
import { Check, FileText, Mail, PackageCheck, RotateCcw, Truck } from "lucide-react";
import { toast } from "sonner";

type Order={id:number;orderNumber:string;customerAlias:string;customerEmail?:string|null;subtotal:number;tax:number;shipping:number;discount:number;total:number;status:string;createdAt:string;items:{id:number;productName:string;quantity:number;unitPrice:number}[];notifications?:{id:number;template:string;deliveryStatus:string;createdAt:string}[]};
const euro=new Intl.NumberFormat("es-ES",{style:"currency",currency:"EUR"});
const steps=["PAGO_SIMULADO","PREPARACIÓN","ENVIADO","ENTREGADO"];
export default function CustomerOrders({email,onShop}:{email:string;onShop:()=>void}){
 const [orders,setOrders]=useState<Order[]>([]),[loading,setLoading]=useState(true),[returning,setReturning]=useState<Order|null>(null),[reason,setReason]=useState("Cambio de opinión"),[details,setDetails]=useState("");
 useEffect(()=>{fetch(`/api/orders?email=${encodeURIComponent(email)}`).then(r=>r.json()).then(d=>setOrders(d.orders||[])).catch(()=>toast.error("No se pudieron cargar tus pedidos")).finally(()=>setLoading(false));},[email]);
 const invoice=async(o:Order)=>{const{jsPDF}=await import("jspdf");const d=new jsPDF();d.setFillColor(16,42,60);d.rect(0,0,210,48,"F");d.setTextColor(255,255,255);d.setFontSize(24);d.text("SENSORIA",16,22);d.setFontSize(10);d.text("FACTURA ACADEMICA · "+o.orderNumber,16,31);d.setTextColor(16,42,60);d.setFontSize(16);d.text("Resumen del pedido",16,65);let y=78;o.items.forEach(i=>{d.setFontSize(10);d.text(`${i.quantity} x ${i.productName}`,18,y);d.text(euro.format(i.quantity*i.unitPrice),190,y,{align:"right"});y+=10;});d.line(16,y,194,y);y+=12;[["Subtotal",o.subtotal],["Descuento",-o.discount],["Envío",o.shipping],["IVA",o.tax],["TOTAL",o.total]].forEach(([l,v])=>{d.text(String(l),140,y,{align:"right"});d.text(euro.format(Number(v)),190,y,{align:"right"});y+=9;});d.setFontSize(8);d.setTextColor(100,110,120);d.text("Documento académico. No constituye una factura fiscal.",16,275);d.save(`Factura-${o.orderNumber}.pdf`);};
 const requestReturn=async(e:React.FormEvent)=>{e.preventDefault();if(!returning)return;const r=await fetch("/api/returns",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({orderId:returning.id,reason,details})});const d=await r.json();if(!r.ok){toast.error(d.error||"No se pudo solicitar");return;}toast.success("Solicitud de devolución registrada");setReturning(null);setDetails("");};
 return <main className="backoffice customer-orders"><div className="backoffice-head"><div><p className="eyebrow">ESPACIO PERSONAL</p><h1>Mis pedidos</h1><p>Historial, facturas, seguimiento y devoluciones de {email}.</p></div><div className="metric"><PackageCheck/><span><b>{orders.length}</b> pedidos</span></div></div>{loading?<div className="admin-empty"><PackageCheck/><h3>Cargando historial…</h3></div>:orders.length===0?<div className="admin-empty"><PackageCheck/><h3>Aún no tienes pedidos</h3><p>Cuando completes una compra aparecerá aquí.</p><button onClick={onShop}>Explorar la tienda</button></div>:<div className="customer-order-list">{orders.map(o=>{const index=Math.max(0,steps.indexOf(o.status));return <article key={o.id}><header><div><span>{o.orderNumber}</span><h2>{new Date(o.createdAt).toLocaleDateString("es-ES",{day:"2-digit",month:"long",year:"numeric"})}</h2></div><strong>{euro.format(o.total)}</strong></header><div className="customer-items">{o.items.map(i=><span key={i.id}><b>{i.quantity}×</b> {i.productName}</span>)}</div><div className="customer-timeline">{steps.map((s,i)=><span className={i<=index?"done":""} key={s}><i>{i<2?<Check/>:i===2?<Truck/>:<PackageCheck/>}</i><b>{s==="PAGO_SIMULADO"?"Confirmado":s.charAt(0)+s.slice(1).toLowerCase()}</b></span>)}</div><div className="customer-order-actions"><button onClick={()=>invoice(o)}><FileText/>Descargar factura</button><button onClick={()=>setReturning(o)} disabled={o.status==="CANCELADO"}><RotateCcw/>Solicitar devolución</button></div>{!!o.notifications?.length&&<p className="customer-notice"><Mail/> {o.notifications.length} avisos registrados · último: {o.notifications.at(-1)?.template.replaceAll('_',' ')}</p>}</article>})}</div>}{returning&&<div className="overlay tool-overlay" onMouseDown={e=>e.target===e.currentTarget&&setReturning(null)}><form className="return-modal" onSubmit={requestReturn}><p className="eyebrow">DEVOLUCIÓN</p><h2>{returning.orderNumber}</h2><p>Cuéntanos el motivo. El reembolso es completamente simulado.</p><label>Motivo<select value={reason} onChange={e=>setReason(e.target.value)}><option>Cambio de opinión</option><option>Producto dañado</option><option>No era lo esperado</option><option>Pedido incorrecto</option></select></label><label>Detalles<textarea value={details} onChange={e=>setDetails(e.target.value)} placeholder="Añade información útil"/></label><div><button type="button" onClick={()=>setReturning(null)}>Cancelar</button><button className="admin-primary">Enviar solicitud</button></div></form></div>}</main>;
}
